### ISSUE TITLE
styling should be done in your CSS

### ISSUE THREAD

**Issue by ad3429** [AddySaurus/prj-rev-bwfs-dasmoto#1]
https://github.com/AddySaurus/prj-rev-bwfs-dasmoto/blob/master/Dasmoto_artsNcrafts/index.html#L21-L44

It seems that you manually styled some elements in your HTML, however all styling should be done in your CSS file. The purpose of using id's and classes, as you have done, is to access those id's/classes in your CSS so that you can assign them specific stylings. Usually web developers try to keep their HTML and CSS/styling separate, so I would recommend doing this.

**Comment by AddySaurus** [comment]
Thank you! I will remember that.
