### ISSUE TITLE
HTML is nicely structured/organized 

### ISSUE THREAD

**Issue by ad3429** [AddySaurus/prj-rev-bwfs-dasmoto#4]
https://github.com/AddySaurus/prj-rev-bwfs-dasmoto/blob/master/Dasmoto_artsNcrafts/index.html#L8-L47

Your HTML is very nicely formatted/organized, and you generally followed good coding practices such as indentation, readability, etc. Make sure to keep up the good work!

**Comment by AddySaurus** [comment]
Thanks! The course is helping me a lot!
