### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by ad3429** [AddySaurus/prj-rev-bwfs-dasmoto#5]
**Summary Grade: Satisfactory, needs some additional work**

Good job! Your files are organized nicely and you did a good job for the most part, but I did notice that you deviated slightly from the client specification so I would definitely go back and make the necessary tweaks to match what the client asked for. 

I have made some comments in your code to take note of. First off, great job making use of id's and classes appropriately -- many learners seem to confuse this concept, so great job getting that right. One area of improvement is you should make sure to comment the main parts of your code in future projects. This greatly helps your development flow, especially as your projects get larger and more complex since they serve as a reminder to why you decided to code something a particular way. Here is a quick refresher on commenting in HTML and CSS, respectively:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/31047417-4cc00f04-a5d8-11e7-9a81-7346f4bbce50.png">

<img width="178" alt="css comment" src="https://user-images.githubusercontent.com/25671399/31047419-4e1f8e56-a5d8-11e7-8894-14517e01086d.png">

I noticed that you manually styled some elements in your HTML and you usually want to avoid this since you want to separate your HTML and styling by having them in separate files. All of your styling should therefore go in your CSS files. It also seems that you have a lot of repetitive CSS, so I would work on condensing this by making use of classes to group elements together and to assign them the same stylings. Here is a great resource to read about how to properly make use of id's and classes in your CSS:

https://css-tricks.com/the-difference-between-id-and-class/

Good job overall! As a further challenge, try using css to design your webpage even further! You did a great job in following the client specification, but for your own practice you should see how creative you can get by taking the design/styling of your site to the next level (for example, you can try experimenting with background colors on your other divs).

**Comment by AddySaurus** [comment]
Thank you for the feedback and additional resources! I got the feeling that I could style the HTML a little more smoothly, including styling exclusively in a .css file. I will work on this going forward. It slipped my mind entirely to comment, now that you mention it, but this is something else I will be conscious of moving forward. Excited to continue !
